image:
  # -- image repository
  repository: ghcr.io/arlintdev/trivy-glass
  # -- image tag
  tag: "latest"
  # -- pull policy
  pullPolicy: Always
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## Example:
  ## pullSecrets:
  ##   - name: myRegistryKeySecretName
  # -- pull secrets
  pullSecrets: []
redis:
  image:
    repository: redis
    tag: 6.2.17
labels:

settings:
  cluster: "yourcluster"
  
serviceAccount:
  create: true
  name: trivy-glass
  annotations: {}

configMap:
  enabled: false
  name: apps-config
  data: |
  