apiVersion: v1
kind: Service
metadata:
  name: {{ include "trivy-glass.name" . }}
  namespace: {{ include "trivy-glass.namespace" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "trivy-glass.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
