name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to main branch (customize as needed)
  pull_request:
    branches:
      - main  # Optional: Build on PRs too

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx (for multi-platform builds, optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Build context (typically root where Dockerfile is)
          file: ./Dockerfile  # Path to Dockerfile
          push: ${{ github.event_name != 'pull_request' }}  # Push only on push, not PR
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          platforms: linux/amd64  # Add linux/arm64, etc., if multi-platform