name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on push to main branch (customize as needed)
  pull_request:
    branches:
      - main # Optional: Build on PRs too
  release:
    types: [published] # Trigger on release publish

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Get short SHA for tagging
      - name: Get short SHA
        id: short_sha
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. Set up Docker Buildx (for multi-platform builds, optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5.1 Build and push the Docker image
      - name: Build and push amd64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:latest-amd64
            ghcr.io/${{ github.repository }}:${{ github.ref_type == 'tag' && github.ref_name || steps.short_sha.outputs.SHA_SHORT }}-amd64
          platforms: linux/amd64

      # 5.2 Build and push the Docker image
      - name: Build and push arm64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:latest-arm64
            ghcr.io/${{ github.repository }}:${{ github.ref_type == 'tag' && github.ref_name || steps.short_sha.outputs.SHA_SHORT }}-arm64
          platforms: linux/arm64/v8

      # 5.3 Build and push the Docker image
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context (typically root where Dockerfile is)
          file: ./Dockerfile # Path to Dockerfile
          push: ${{ github.event_name != 'pull_request' }} # Push only on push, not PR
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_type == 'tag' && github.ref_name || steps.short_sha.outputs.SHA_SHORT }}
          platforms: linux/amd64,linux/arm64/v8
