name: test
permissions:
  contents: read
on:
  push:
    branches-ignore: ['main']

jobs:
  test-ts:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout 🛒
        uses: actions/checkout@v6

      - name: node 22 ❇️
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: install ♦️
        run: |
          npm ci

      - name: lint 🧹
        run: |
          npm run lint
